compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@metabridge/cli@*":
    dependencies:
      "@metabridge/plugin-kotlin": "*"
      "@metabridge/plugin-swift": "*"
      "@metabridge/plugin-typescript": "*"
      "@metabridge/plugin-typescript-docs": "*"
  "@rjsf/chakra-ui@*":
    dependencies:
      "@chakra-ui/form-control": "*"
      "@chakra-ui/icon": "*"
      "@chakra-ui/layout": "*"
      "@chakra-ui/menu": "*"
      "@chakra-ui/spinner": "*"
      "@chakra-ui/system": "*"
      "@emotion/cache": "*"
      "@emotion/react": "*"
      "@emotion/styled": "*"
      "@emotion/weak-memoize": "*"
      react-dom: "*"
  quicktype-core@*:
    dependencies:
      lodash: "*"

yarnPath: .yarn/releases/yarn-4.0.1.cjs
