packageExtensions:
  "@metabridge/cli@*":
    dependencies:
      "@metabridge/plugin-typescript": "*"
      "@metabridge/plugin-typescript-docs": "*"
      "@metabridge/plugin-kotlin": "*"
      "@metabridge/plugin-swift": "*"
  "@rjsf/chakra-ui@*":
    dependencies:
      "@chakra-ui/form-control": "*"
      "@chakra-ui/icon": "*"
      "@chakra-ui/layout": "*"
      "@chakra-ui/menu": "*"
      "@chakra-ui/spinner": "*"
      "@chakra-ui/system": "*"
      "@emotion/cache": "*"
      "@emotion/react": "*"
      "@emotion/styled": "*"
      "@emotion/weak-memoize": "*"
      react-dom: "*"
  "quicktype-core@*":
    dependencies:
      "lodash": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
