compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@rjsf/chakra-ui@*":
    peerDependencies:
      "@emotion/react": "*"
      "@emotion/cache": "*"
      "@emotion/weak-memoize": "*"
      "@emotion/styled": "*"
  "@chakra-ui/system@*":
    peerDependencies:
      "@emotion/styled": "*"
  "chakra-react-select@*":
    peerDependencies:
      "@emotion/styled": "*"
      "framer-motion": "*"
      

yarnPath: .yarn/releases/yarn-4.8.1.cjs
