import assert from "assert";
import dedent from "dedent";
import exec from "exec-sh";
import fs from "fs/promises";
import path from "path";

(async () => {
  const command = [
    "yarn",
    "metabridge-cli",
    "--plugin",
    "@metabridge/plugin-typescript",
    "--schema",
    "./test/schema.json",
    "--output",
    "./test/schema.output.ts",
  ].join(" ");

  await exec.promise(command, true);

  const output = await fs.readFile(
    path.resolve("./test/schema.output.ts"),
    "utf-8"
  );

  assert.equal(
    output,
    dedent`
      /* tslint:disable */
      /**
       * This file was automatically generated by json-schema-to-typescript.
       * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
       * and run json-schema-to-typescript to regenerate this file.
       */
      
      export interface MyAppBridgeSchema {
        StorageGetRequestBody: {
          key: string;
        };
        StorageGetResponse: StringValue;
      }
      export interface StringValue {
        value: string;
      }
      
      export interface MetaBridgeDriver {
        onCalled: (type: string, requestBody: any) => Promise<any>;
      }
      
      export function makeMyAppBridge<T extends MetaBridgeDriver>({
        driver,
      }: {
        driver: T;
      }) {
        return {
          driver,
          /**
           * Get item from persistent storage
           */
          getItemFromStorage(
            req: MyAppBridgeSchema["StorageGetRequestBody"]
          ): Promise<MyAppBridgeSchema["StorageGetResponse"]> {
            return driver.onCalled("STORAGE.GET", req);
          },
        };
      }
    ` + "\n"
  );
})();
